Ajustar pipeline para manter padronização e ordem de steps

diff --git a/.github/workflows/order-pipeline.yml b/.github/workflows/order-pipeline.yml
--- a/.github/workflows/order-pipeline.yml
+++ b/.github/workflows/order-pipeline.yml
@@ -14,9 +14,8 @@ env:
   EKS_CLUSTER_NAME: 'ez-fastfood-cluster-dev'
 
 jobs:
-  setup-jdk:
+  setup-environment-tools:
     runs-on: ubuntu-latest
-
     steps:
       - name: Set up JDK
         uses: actions/setup-java@v3
@@ -24,10 +23,9 @@ jobs:
           distribution: 'temurin'
           java-version: ${{ env.JAVA_VERSION }}
 
-  build-package:
-    needs: setup-jdk
+  build-artifact:
+    needs: setup-environment-tools
     runs-on: ubuntu-latest
-
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
@@ -41,8 +39,11 @@ jobs:
       - name: Build with Maven
         run: mvn -f ./pom.xml clean package -Pprd
 
-  run-tests:
-    needs: build-package
+      - name: Build with Maven
+        run: mvn -f ./pom.xml clean package -Pprd
+
+  unit-tests:
+    needs: build-artifact
     runs-on: ubuntu-latest
     if: github.ref == 'refs/heads/develop'
     steps:
@@ -59,15 +60,11 @@ jobs:
         run: mvn test
 
       - name: Generate Test Report
-        run: |
-          mvn surefire-report:report-only
-          ls -lha
+        run: mvn surefire-report:report-only
 
       - name: Show Test Results in Logs
         if: always()
-        run: |
-          echo "========= Surefire Test Results ========="
-          cat target/surefire-reports/*.txt || echo "No test results found"
+        run: cat target/surefire-reports/*.txt || echo "No test results found"
 
       - name: Upload Test Report as Artifact
         uses: actions/upload-artifact@v4
@@ -75,41 +72,43 @@ jobs:
           name: test-report
           path: target/surefire-reports
 
-  run-sonar-analysis:
-    needs: run-tests
+  static-code-analysis:
+    needs: unit-tests
     runs-on: ubuntu-latest
-    if: github.ref == 'refs/heads/develop'
+    if: github.ref == 'refs/heads/develop' 
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
 
-      - name: SonarQube Scan
+      - name: Run SonarQube Scan
         run: mvn clean verify sonar:sonar -Dsonar.token=${{ env.SONAR_TOKEN }}
 
-      - name: ⏳ Aguardando processamento do SonarCloud
+      - name: Wait for SonarCloud Processing
         run: sleep 10
-      - name: 🔍 Verificando status do Quality Gate no SonarQube
+
+      - name: Check SonarQube Quality Gate Status
         run: |
           response=$(curl -s -u "$SONAR_TOKEN:" "https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ env.SONAR_PROJECT_KEY }}")
           status=$(echo "$response" | jq -r '.projectStatus.status')
-          
-          echo "🚦 Status do Quality Gate: $status"
-          
+
+          echo "Quality Gate Status: $status"
+
           if [[ "$status" != "OK" ]]; then
-            echo "❌ O Quality Gate falhou!"
+            echo "❌ Quality Gate failed!"
             exit 1
           fi
-      - name: ✅ Pipeline finalizado com sucesso
-        run: echo "🎉 Tudo certo! O Quality Gate foi aprovado."
 
-  build-and-push-image:
-    needs: run-sonar-analysis
+      - name: ✅ SonarQube Passed
+        run: echo "🎉 Quality Gate Passed."
+
+  docker-build-push:
     runs-on: ubuntu-latest
+    if: contains('refs/heads/develop', github.ref) || contains('refs/heads/main', github.ref)
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
 
-      - name: Set up Docker Buildx
+      - name: Set up Docker Build
         uses: docker/setup-buildx-action@v3
 
       - name: Log in to Docker Hub
@@ -124,20 +123,23 @@ jobs:
           context: .
           file: ./Dockerfile
           push: true
-          tags: dasilvathaynara/ez-fastfood-order-ms:latest
+          tags: ${{ env.DOCKER_FILE_TAG }}
 
-  deploy:
-    needs: build-and-push-image
+  deploy-to-eks:
+    needs: docker-build-push
     runs-on: ubuntu-latest
+    if: contains('refs/heads/develop', github.ref) || contains('refs/heads/main', github.ref)
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
+
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v2
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-east-1
+
       - name: Install kubectl
         run: |
           curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
@@ -145,7 +147,7 @@ jobs:
           sudo mv kubectl /usr/local/bin/
 
       - name: Update kubeconfig for EKS
-        run: aws eks update-kubeconfig --region us-east-1 --name ${{env.EKS_CLUSTER_NAME}}
+        run: aws eks update-kubeconfig --region us-east-1 --name ${{ env.EKS_CLUSTER_NAME }}
 
       - name: Apply Kubernetes manifests
         run: |
